# Generated by Django 5.2.8 on 2025-11-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_fname', models.CharField(max_length=100)),
                ('emp_lname', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_number', models.BigIntegerField(max_length=100)),
                ('emp_birth', models.DateField(default=None)),
                ('emp_address', models.CharField(max_length=500)),
                ('emp_country', models.CharField(max_length=100)),
                ('emp_city', models.CharField(max_length=100)),
                ('emp_ocity', models.CharField(default=None)),
                ('emp_skills', models.CharField(max_length=500)),
            ],
        ),
    ]
