# Generated by Django 5.2.8 on 2025-11-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jala_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_ocity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
