# Generated by Django 5.2.8 on 2025-12-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jala_app', '0002_alter_employees_emp_number_alter_employees_emp_ocity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=200)),
                ('image', models.FileField(default=None, upload_to='')),
            ],
        ),
    ]
