# Generated by Django 5.2.8 on 2025-12-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jala_app', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(default='img.jpeg', upload_to=''),
        ),
    ]
